#root/ [PATH in config]
#   |
#   |_ data/
#   |     |_filename [in config]
#   |
#   |_ main/
#   |     |_ANALOGY_SCIENTIFIC [Git repo]
#   |     |_IncPrev.py [IncPrev script]
#   |
#   |_ out/

PATH: !!str "./"
dir_data: !!str "data/"
dir_main: !!str "main/"
dir_out: !!str "out/"

processing:
  filename: !!str "IncPrev281conditions_Goldv5_fullDB20231010024904.csv"

incprev:
  filename: "dat_processed.parquet"

  # The dates below should be same as the value entered in dexter for data extract.
  start_date:
    inc:
        year: !!int 2001
        month: !!int 1
        day: !!int 1
    prev:
        year: !!int 2001
        month: !!int 7
        day: !!int 1
  end_date:
    inc:
        year: !!int 2021
        month: !!int 12
        day: !!int 31
    prev:
        year: !!int 2021
        month: !!int 12
        day: !!int 31

  merge_EthOtherMixed: !!bool True
  database: !!str "GOLD"

  # How many parallel processes to run
  # Note: Each process will load the input data into memory, so is memory intensive
  n_processes: !!int 1

  BD_LIST: {'1': ['BD_MEDI:CPRD_GOLD_CANCERLALLFUL_NOSCCBCC:0',
  'BD_MEDI:CPRD_GOLD_CANCERLALLFUL_NOSCCBCC2:1',
  'BD_MEDI:CPRD_PRI_OROPH:2',
  'BD_MEDI:CPRD_THYROID:3',
  'BD_MEDI:CPRD_NHL:4',
  'BD_MEDI:CPRD_ENTHESOPATHY:5',
  'BD_MEDI:CPRD_TIA:6',
  'BD_MEDI:CPRD_OTH_HAEM_ANAEMIA:7',
  'BD_MEDI:CPRD_RH_FEVER:8',
  'BD_MEDI:CPRD_PERIPH_NEURO:9',
  'BD_MEDI:CPRD_OA:10'],
 '2': ['BD_MEDI:CPRD_COPD:11',
  'BD_MEDI:CPRD_CATARACT:12',
  'BD_MEDI:CPRD_VTE_EX_PE:13',
  'BD_MEDI:CPRD_BLIND:14',
  'BD_MEDI:CPRD_DEAF:15',
  'BD_MEDI:CPRD_SUBSTANCE_MISUSE:16',
  'BD_MEDI:CPRD_INTERVERT_DISC:17',
  'BD_MEDI:CPRD_RAYNAUDS:18',
  'BD_MEDI:CPRD_FRACTURE_WRIST:19',
  'BD_MEDI:CPRD_PRI_OTHER:20',
  'BD_MEDI:CPRD_TRIFASC_BLOCK:21'],
 '3': ['BD_MEDI:CPRD_CIRRHOSIS:22',
  'BD_MEDI:CPRD_DERMATITIS:23',
  'BD_MEDI:CPRD_PRI_BONE:24',
  'BD_MEDI:CPRD_PERITONITIS:25',
  'BD_MEDI:CPRD_CHRONIC_FATIGUE:26',
  'BD_MEDI:CPRD_HODGKINS:27',
  'BD_MEDI:CPRD_CF:28',
  'BD_MEDI:CPRD_TB:29',
  'BD_MEDI:CPRD_LIVER_ALC:30',
  'BD_MEDI:CPRD_NONRH_AORTIC:31',
  'BD_MEDI:CPRD_MS:32'],
 '4': ['BD_MEDI:CPRD_GN:33',
  'BD_MEDI:CPRD_HERNIA_ABDO:34',
  'BD_MEDI:CPRD_OTH_ANAEMIA:35',
  'BD_MEDI:CPRD_PRI_STOMACH:36',
  'BD_MEDI:CPRD_OESOPH_ULC:37',
  'BD_MEDI:CPRD_CEREBRAL_PALSY:38',
  'BD_MEDI:CPRD_STROKE_NOS:39',
  'BD_MEDI:CPRD_INTELL_DZ:40',
  'BD_MEDI:CPRD_EPILEPSY:41',
  'BD_MEDI:CPRD_SLE:42',
  'BD_MEDI:CPRD_ESRD:43'],
 '5': ['BD_MEDI:CPRD_GLAUCOMA:44',
  'BD_MEDI:CPRD_PRI_BRAIN:45',
  'BD_MEDI:CPRD_HIV:46',
  'BD_MEDI:CPRD_DIAB_EYE:47',
  'BD_MEDI:CPRD_FRACTURE_HIP:48',
  'BD_MEDI:CPRD_RHA:49',
  'BD_MEDI:CPRD_MULT_VALVE:50',
  'BD_MEDI:CPRD_HF:51',
  'BD_MEDI:CPRD_GOUT:52',
  'BD_MEDI:CPRD_CHR_HEP:53',
  'BD_MEDI:CPRD_BIFASC_BLOCK:54'],
 '6': ['BD_MEDI:CPRD_LEUKAEMIA:55',
  'BD_MEDI:CPRD_CARDIOMYO_OTH:56',
  'BD_MEDI:CPRD_ASBESTOSIS:57',
  'BD_MEDI:CPRD_PLEURAL_PLAQUE:58',
  'BD_MEDI:CPRD_MENORRHAGIA:59',
  'BD_MEDI:CPRD_SPINA_BIFIDA:60',
  'BD_MEDI:CPRD_DEPRESSION:61',
  'BD_MEDI:CPRD_ADHD:62',
  'BD_MEDI:CPRD_PARKINSONS:63',
  'BD_MEDI:CPRD_INTRAUTERINE_HYPOXIA:64',
  'BD_MEDI:CPRD_APPENDICITIS:65'],
 '7': ['BD_MEDI:CPRD_PRI_MELANOMA:66',
  'BD_MEDI:CPRD_ASPIRATION_PNEUMO:67',
  'BD_MEDI:CPRD_SPONDYLOSIS:68',
  'BD_MEDI:CPRD_HAEMANGIOMA:69',
  'BD_MEDI:CPRD_SCLERITIS:70',
  'BD_MEDI:CPRD_DOWNS:71',
  'BD_MEDI:CPRD_DM_NEURO:72',
  'BD_MEDI:CPRD_PLASMACELL:73',
  'BD_MEDI:CPRD_CONGENITAL_SEPTAL:74',
  'BD_MEDI:CPRD_FIBROMATOSIS:75',
  'BD_MEDI:CPRD_TIN:76'],
 '8': ['BD_MEDI:CPRD_CHOLECYSTITIS:77',
  'BD_MEDI:CPRD_KERATITIS:78',
  'BD_MEDI:CPRD_UROLITHIASIS:79',
  'BD_MEDI:CPRD_FEMALE_INFERTILITY:80',
  'BD_MEDI:CPRD_MALE_INFERTILITY:81',
  'BD_MEDI:CPRD_PRI_KIDNEY:82',
  'BD_MEDI:CPRD_SEC_LN:83',
  'BD_MEDI:CPRD_PRI_BOWEL:84',
  'BD_MEDI:CPRD_SCHIZO:85',
  'BD_MEDI:CPRD_PRI_PROST:86',
  'BD_MEDI:CPRD_ACNE:87'],
 '9': ['BD_MEDI:CPRD_REACTIVE:88',
  'BD_MEDI:CPRD_OSTEOPOROSIS:89',
  'BD_MEDI:CPRD_ULCER_PEPTIC:90',
  'BD_MEDI:CPRD_HYPOSPLENISM:91',
  'BD_MEDI:CPRD_LBW:92',
  'BD_MEDI:CPRD_ED:93',
  'BD_MEDI:CPRD_COELIAC:94',
  'BD_MEDI:CPRD_AV_BLOCK_2:95',
  'BD_MEDI:CPRD_PRI_SKIN:96',
  'BD_MEDI:CPRD_PRI_BREAST:97',
  'BD_MEDI:CPRD_FEMALE_GENITAL_PROLAPSE:98'],
 '10': ['BD_MEDI:CPRD_MDS:99',
  'BD_MEDI:CPRD_PE:100',
  'BD_MEDI:CPRD_APLASTIC:101',
  'BD_MEDI:CPRD_PRI_OVARIAN:102',
  'BD_MEDI:CPRD_ANORECTAL_PROLAPSE:103',
  'BD_MEDI:CPRD_NEO_JAUNDICE:104',
  'BD_MEDI:CPRD_MACULA_DEGEN:105',
  'BD_MEDI:CPRD_ANXIETY:106',
  'BD_MEDI:CPRD_MIGRAINE:107',
  'BD_MEDI:CPRD_FATTY_LIVER:108',
  'BD_MEDI:CPRD_PULM_FIBROSIS:109'],
 '11': ['BD_MEDI:CPRD_GORD:110',
  'BD_MEDI:CPRD_OBESITY:111',
  'BD_MEDI:CPRD_PRI_LUNG:112',
  'BD_MEDI:CPRD_AUTONOMIC_NEURO:113',
  'BD_MEDI:CPRD_BAD:114',
  'BD_MEDI:CPRD_MGUS:115',
  'BD_MEDI:CPRD_IMMUNODEF:116',
  'BD_MEDI:CPRD_PRI_SKIN_NO_BCC:117',
  'BD_MEDI:CPRD_OBSTR_REFLUX:118',
  'BD_MEDI:CPRD_ULC_COLITIS:119',
  'BD_MEDI:CPRD_CHOLANGITIS:120'],
 '12': ['BD_MEDI:CPRD_GCA:121',
  'BD_MEDI:CPRD_PANCREATITIS:122',
  'BD_MEDI:CPRD_ALLERGIC_RHINITIS:123',
  'BD_MEDI:CPRD_IBS:124',
  'BD_MEDI:CPRD_ALC_PROBLEMS:125',
  'BD_MEDI:CPRD_PRI_MESOTHELIOMA:126',
  'BD_MEDI:CPRD_PD:127',
  'BD_MEDI:CPRD_ISCH_STROKE:128',
  'BD_MEDI:CPRD_PERICARDIAL_EFFUSION:129',
  'BD_MEDI:CPRD_PSORIASIS:130',
  'BD_MEDI:CPRD_CARPAL_TUNNEL:131'],
 '13': ['BD_MEDI:CPRD_PRI_BLADDER:132',
  'BD_MEDI:CPRD_THALA:133',
  'BD_MEDI:CPRD_SINUSITIS:134',
  'BD_MEDI:CPRD_BENIGN_OVARY:135',
  'BD_MEDI:CPRD_PTH:136',
  'BD_MEDI:CPRD_VARICES:137',
  'BD_MEDI:CPRD_PRI_BILIARY:138',
  'BD_MEDI:CPRD_RH_VALVE:139',
  'BD_MEDI:CPRD_ANT_UVEITIS:140',
  'BD_MEDI:CPRD_THROMBOPHILIA:141',
  'BD_MEDI:CPRD_SYS_SCLEROSIS:142'],
 '14': ['BD_MEDI:CPRD_PDA:143',
  'BD_MEDI:CPRD_PRI_OESOPH:144',
  'BD_MEDI:CPRD_DEMENTIA:145',
  'BD_MEDI:CPRD_SPINAL_STENOSIS:146',
  'BD_MEDI:CPRD_PREMATURITY:147',
  'BD_MEDI:CPRD_URINE_INCONT:148',
  'BD_MEDI:CPRD_ASTHMA:149',
  'BD_MEDI:CPRD_SPLENOMEGALY:150',
  'BD_MEDI:CPRD_HBW:151',
  'BD_MEDI:CPRD_CIN_CERVICAL:152',
  'BD_MEDI:CPRD_PRI_LIVER:153'],
 '15': ['BD_MEDI:CPRD_INTRACEREB_HAEM:154',
  'BD_MEDI:CPRD_NEURO_BLADDER:155',
  'BD_MEDI:CPRD_SUBARACH:156',
  'BD_MEDI:CPRD_PLEURAL_EFFUSION:157',
  'BD_MEDI:CPRD_MND:158',
  'BD_MEDI:CPRD_GASTRITIS_DUODENITIS:159',
  'BD_MEDI:CPRD_UNDESCENDED_TESTIS:160',
  'BD_MEDI:CPRD_POST_UVEITIS:161',
  'BD_MEDI:CPRD_HERNIA_DIAPHRAGM:162',
  'BD_MEDI:CPRD_SEC_BOWEL:163',
  'BD_MEDI:CPRD_AUTISM:164'],
 '16': ['BD_MEDI:CPRD_PILONIDAL:165',
  'BD_MEDI:CPRD_CROHNS:166',
  'BD_MEDI:CPRD_B12_DEF:167',
  'BD_MEDI:CPRD_ACTINIC_KERATOSIS:168',
  'BD_MEDI:CPRD_HYDROCELE:169',
  'BD_MEDI:CPRD_CHR_CYSTITIS:170',
  'BD_MEDI:CPRD_BENIGN_COLON:171',
  'BD_MEDI:CPRD_PCOS:172',
  'BD_MEDI:CPRD_DYSMENORRHOEA:173',
  'BD_MEDI:CPRD_COLLAPSED_VERT:174',
  'BD_MEDI:CPRD_SCOLIOSIS:175'],
 '17': ['BD_MEDI:CPRD_BENIGN_BRAIN:176',
  'BD_MEDI:CPRD_THAL_TRAIT:177',
  'BD_MEDI:CPRD_NASAL_POLYP:178',
  'BD_MEDI:CPRD_URTICARIA:179',
  'BD_MEDI:CPRD_RETINAL_VASC_OCCL:180',
  'BD_MEDI:CPRD_RETINAL_DETACH:181',
  'BD_MEDI:CPRD_ENDOMETRIOSIS:182',
  'BD_MEDI:CPRD_PRI_THROMBOCYTOPAENIA:183',
  'BD_MEDI:CPRD_SVT:184',
  'BD_MEDI:CPRD_PCB:185',
  'BD_MEDI:CPRD_PSA:186'],
 '18': ['BD_MEDI:CPRD_LEIOMYOMA:187',
  'BD_MEDI:CPRD_JUV_ARTH:188',
  'BD_MEDI:CPRD_NONRH_MITRAL:189',
  'BD_MEDI:CPRD_BENIGN_UTERUS:190',
  'BD_MEDI:CPRD_TINNITUS:191',
  'BD_MEDI:CPRD_PMR:192',
  'BD_MEDI:CPRD_BENIGN_STOMACH:193',
  'BD_MEDI:CPRD_SEC_LIVER:194',
  'BD_MEDI:CPRD_PRI_TESTIS:195',
  'BD_MEDI:CPRD_ROSACEA:196',
  'BD_MEDI:CPRD_ANORECTAL_FISTULA:197'],
 '19': ['BD_MEDI:CPRD_2RY_POLYCYTHAEMIA:198',
  'BD_MEDI:CPRD_AUTOIMM_LIVER:199',
  'BD_MEDI:CPRD_IDA:200',
  'BD_MEDI:CPRD_PNEUMOTHORAX:201',
  'BD_MEDI:CPRD_OCD:202',
  'BD_MEDI:CPRD_VOLVULUS:203',
  'BD_MEDI:CPRD_BRONCHIECTASIS:204',
  'BD_MEDI:CPRD_RESP_FAILURE:205',
  'BD_MEDI:CPRD_ENDOMETRIAL_HYPER:206',
  'BD_MEDI:CPRD_BPH:207',
  'BD_MEDI:CPRD_LIVER_FAIL:208'],
 '20': ['BD_MEDI:CPRD_LICHEN_PLANUS:209',
  'BD_MEDI:CPRD_PTOSIS:210',
  'BD_MEDI:CPRD_MENIERE:211',
  'BD_MEDI:CPRD_BELLS:212',
  'BD_MEDI:CPRD_PCV:213',
  'BD_MEDI:CPRD_PRI_UTERINE:214',
  'BD_MEDI:CPRD_DELIRIUM:215',
  'BD_MEDI:CPRD_ENTERO_ARTHRO:216',
  'BD_MEDI:CPRD_AGRANULOCYTOSIS:217',
  'BD_MEDI:CPRD_SUBDURAL_HAEM:218',
  'BD_MEDI:CPRD_SEC_BONE:219'],
 '21': ['BD_MEDI:CPRD_SEB_DERM:220',
  'BD_MEDI:CPRD_SLEEP_APNOEA:221',
  'BD_MEDI:CPRD_EATING_DZ:222',
  'BD_MEDI:CPRD_ALOPECIA_AREATA:223',
  'BD_MEDI:CPRD_FOLATEDEF:224',
  'BD_MEDI:CPRD_POST_TERM:225',
  'BD_MEDI:CPRD_PRI_CERVICAL:226',
  'BD_MEDI:CPRD_AV_BLOCK_3:227',
  'BD_MEDI:CPRD_ESSENTIAL_TREMOR:228',
  'BD_MEDI:CPRD_SARCOID:229',
  'BD_MEDI:CPRD_RDN:230'],
 '22': ['BD_MEDI:CPRD_MYASTHENIA:231',
  'BD_MEDI:CPRD_HIDRADENITIS:232',
  'BD_MEDI:CPRD_VT:233',
  'BD_MEDI:CPRD_PULM_COLLAPSE:234',
  'BD_MEDI:CPRD_PRI_PANCR:235',
  'BD_MEDI:CPRD_HOCM:236',
  'BD_MEDI:CPRD_HYPER_NASAL_TURBS:237',
  'BD_MEDI:CPRD_PRI_THYROID:238',
  'BD_MEDI:CPRD_RBBB:239',
  'BD_MEDI:CPRD_SEC_ADRENAL:240',
  'BD_MEDI:CPRD_SEC_LUNG:241'],
 '23': ['BD_MEDI:CPRD_VITILIGO:242',
  'BD_MEDI:CPRD_INTRACRANIAL_HTN:243',
  'BD_MEDI:CPRD_BARRETTS:244',
  'BD_MEDI:CPRD_DCM:245',
  'BD_MEDI:CPRD_PORTAL_HTN:246',
  'BD_MEDI:CPRD_PRI_MULTINDEP:247',
  'BD_MEDI:CPRD_ANGIODYSPLASIA_COLON:248',
  'BD_MEDI:CPRD_SICKLE_CELL:249',
  'BD_MEDI:CPRD_SEC_OTHER:250',
  'BD_MEDI:CPRD_SEC_PULM_HTN:251',
  'BD_MEDI:CPRD_SPONDYLOLISTHESIS:252'],
 '24': ['BD_MEDI:CPRD_SICKLE_TRAIT:253',
  'BD_MEDI:CPRD_SEC_OTH_THROMBOCYTOPAENIA:254',
  'BD_MEDI:CPRD_SEPSIS_NEWBORN:255',
  'BD_MEDI:CPRD_TRIGEM_NEUR:256',
  'BD_MEDI:CPRD_AV_BLOCK_1:257',
  'BD_MEDI:CPRD_PMB:258',
  'BD_MEDI:CPRD_SEC_PLEURA:259',
  'BD_MEDI:CPRD_LBBB:260',
  'BD_MEDI:CPRD_SJOGREN:261',
  'BD_MEDI:CPRD_ANK_SPOND:262',
  'BD_MEDI:CPRD_PRIM_PULM_HTN:263'],
 '25': ['BD_MEDI:CPRD_SEC_PERITONEUM:264',
  'BD_MEDI:CPRD_SEC_BRAIN:265',
  # 'BD_MEDI:CPRD_2RY_POLYCYTHAEMIA:266', #Removed due to duplicate condition
  'BD_MEDI:CPRD_AAA:267',
  'BD_MEDI:CPRD_AF:268',
  'BD_MEDI:CPRD_ANAL_FISSURE:269',
  'BD_MEDI:CPRD_B12_DEF:270',
  'BD_MEDI:CPRD_CHD_NOS:271',
  'BD_MEDI:CPRD_CHOLELITHIASIS:272',
  'BD_MEDI:CPRD_DIABETES:273',
  'BD_MEDI:CPRD_DIVERTICULI:274'],
 '26': ['BD_MEDI:CPRD_HYPERTENSION:275',
  'BD_MEDI:CPRD_MYOCARDIAL_INFARCTION:276',
  'BD_MEDI:CPRD_PERIPHERAL_ARTERIAL_DISEASE:277',
  'BD_MEDI:CPRD_SICK_SINUS:278',
  'BD_MEDI:CPRD_STABLE_ANGINA:279',
  'BD_MEDI:CPRD_UNSTABLE_ANGINA:280',
  'BD_MEDI:TYPE1DM_11_3_21_BIRM_CAM:281',
  'BD_MEDI:TYPE2DIABETES_11_3_21_BIRM_CAM:282',
  'BD_MEDI:PIDKOO:283',
  'BD_MEDI:HYPERTHYROIDISM_V2_BIRM_CAM:284',
  'BD_MEDI:HYPOTHYROIDISM_MM:285']} 

  #if using parquet input, make sure is_parquet==True and fileType=="parquet"
  is_parquet: !!bool True
  fileType: !!str "parquet"

  # readType only relevant when usePolars is True
  usePolars: !!bool False

  batch_size: !!int 50 # how many conditions to process in each paralel process
  INCREMENT_BY_MONTH: !!int 12
  calc_grouped: !!bool True
  DEMOGRAPHY: # edit below, using this format
    #if no DEMOGRAPHY, set as empty list []
    - "AGE_CATEGORY"
    - "SEX"
    - "IMD_pracid"
    - "HEALTH_AUTH"
    - "ETHNICITY"
    - ['SEX', 'ETHNICITY', 'IMD_pracid']
    - ['AGE_CATEGORY', 'SEX']
    - ['AGE_CATEGORY', 'SEX', 'IMD_pracid']
    - ['AGE_CATEGORY', 'SEX', 'ETHNICITY']
    - ['AGE_CATEGORY', 'SEX', 'HEALTH_AUTH']
    - ['AGE_CATEGORY', 'SEX', 'ETHNICITY', 'HEALTH_AUTH']
    - ['AGE_CATEGORY', 'SEX', 'ETHNICITY', 'IMD_pracid']
    - ['AGE_CATEGORY', 'SEX', 'HEALTH_AUTH', 'IMD_pracid']
